#!/bin/sh

set -e

. ./terraform.conf

# HWE starts with y, Y or 1?
if [ "$HWE" = "yes" ]; then
    KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
else
    KERNEL_FLAVORS="generic"
fi

HOOKS="update-apt-file-cache update-apt-xapian-index update-mlocate-database remove-dbus-machine-id remove-openssh-server-host-keys remove-udev-persistent-rules"

lb config noauto \
    --architecture "$ARCH" \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --keyring-packages ubuntu-keyring \
    --build-with-chroot false \
    --linux-flavours "$KERNEL_FLAVORS" \
    --distribution "$BASECODENAME" \
    --hooks "$HOOKS" \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --memtest none \
    --mode ubuntu \
    --parent-archive-areas "main restricted universe multiverse" \
    --source false \
    --zsync false

# replace channel and suite
sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
